/**
 * CalcWise Calculator Search Index
 * Used for site-wide calculator search functionality
 */
const CALCULATOR_INDEX = [
  // Real Estate
  { name: "Mortgage Calculator", category: "Real Estate", url: "/real-estate-calculators/mortgage-calculator/", keywords: ["mortgage", "home loan", "monthly payment"] },
  { name: "Affordability Calculator", category: "Real Estate", url: "/real-estate-calculators/affordability-calculator/", keywords: ["afford", "home price", "how much"] },
  { name: "Rent vs Buy Calculator", category: "Real Estate", url: "/real-estate-calculators/rent-vs-buy-calculator/", keywords: ["rent", "buy", "renting", "buying"] },
  { name: "Refinance Calculator", category: "Real Estate", url: "/real-estate-calculators/refinance-calculator/", keywords: ["refinance", "refi", "new rate"] },
  { name: "Closing Cost Calculator", category: "Real Estate", url: "/real-estate-calculators/closing-cost-calculator/", keywords: ["closing costs", "settlement"] },
  { name: "Property Tax Calculator", category: "Real Estate", url: "/real-estate-calculators/property-tax-calculator/", keywords: ["property tax", "real estate tax"] },
  { name: "Down Payment Calculator", category: "Real Estate", url: "/real-estate-calculators/down-payment-calculator/", keywords: ["down payment", "deposit"] },
  { name: "Amortization Calculator", category: "Real Estate", url: "/real-estate-calculators/amortization-calculator/", keywords: ["amortization", "schedule", "payoff"] },
  { name: "Cap Rate Calculator", category: "Real Estate", url: "/real-estate-calculators/cap-rate-calculator/", keywords: ["cap rate", "capitalization", "investment property"] },
  { name: "Rental Cash Flow Calculator", category: "Real Estate", url: "/real-estate-calculators/rental-cash-flow-calculator/", keywords: ["rental", "cash flow", "income property"] },
  { name: "ROI Calculator for Rental Property", category: "Real Estate", url: "/real-estate-calculators/rental-property-roi-calculator/", keywords: ["roi", "return", "rental investment"] },
  { name: "Airbnb Income Calculator", category: "Real Estate", url: "/real-estate-calculators/airbnb-income-calculator/", keywords: ["airbnb", "short term rental", "vacation rental"] },
  { name: "House Flip Profit Calculator", category: "Real Estate", url: "/real-estate-calculators/house-flip-calculator/", keywords: ["house flip", "flip profit", "fix and flip"] },
  { name: "Real Estate Commission Calculator", category: "Real Estate", url: "/real-estate-calculators/commission-calculator/", keywords: ["commission", "agent fee", "realtor"] },

  // Finance
  { name: "Loan Calculator", category: "Finance", url: "/finance-calculators/loan-calculator/", keywords: ["loan", "borrow", "payment"] },
  { name: "Interest Calculator", category: "Finance", url: "/finance-calculators/interest-calculator/", keywords: ["interest", "simple interest"] },
  { name: "Compound Interest Calculator", category: "Finance", url: "/finance-calculators/compound-interest-calculator/", keywords: ["compound interest", "growth"] },
  { name: "Savings Calculator", category: "Finance", url: "/finance-calculators/savings-calculator/", keywords: ["savings", "save", "goal"] },
  { name: "Investment Return Calculator", category: "Finance", url: "/finance-calculators/investment-return-calculator/", keywords: ["investment", "return", "portfolio"] },
  { name: "Debt Payoff Calculator", category: "Finance", url: "/finance-calculators/debt-payoff-calculator/", keywords: ["debt", "payoff", "pay off"] },
  { name: "Credit Card Payoff Calculator", category: "Finance", url: "/finance-calculators/credit-card-payoff-calculator/", keywords: ["credit card", "payoff", "minimum payment"] },
  { name: "Net Worth Calculator", category: "Finance", url: "/finance-calculators/net-worth-calculator/", keywords: ["net worth", "assets", "liabilities"] },
  { name: "Budget Calculator", category: "Finance", url: "/finance-calculators/budget-calculator/", keywords: ["budget", "spending", "50/30/20"] },
  { name: "Emergency Fund Calculator", category: "Finance", url: "/finance-calculators/emergency-fund-calculator/", keywords: ["emergency fund", "rainy day"] },
  { name: "Retirement Savings Calculator", category: "Finance", url: "/finance-calculators/retirement-savings-calculator/", keywords: ["retirement", "401k", "ira"] },
  { name: "Inflation Calculator", category: "Finance", url: "/finance-calculators/inflation-calculator/", keywords: ["inflation", "purchasing power"] },
  { name: "Salary to Hourly Calculator", category: "Finance", url: "/finance-calculators/salary-to-hourly-calculator/", keywords: ["salary", "hourly", "wage"] },

  // Business
  { name: "Profit Margin Calculator", category: "Business", url: "/business-calculators/profit-margin-calculator/", keywords: ["profit", "margin", "revenue"] },
  { name: "Markup Calculator", category: "Business", url: "/business-calculators/markup-calculator/", keywords: ["markup", "cost", "price"] },
  { name: "Break Even Calculator", category: "Business", url: "/business-calculators/break-even-calculator/", keywords: ["break even", "breakeven"] },
  { name: "ROI Calculator", category: "Business", url: "/business-calculators/roi-calculator/", keywords: ["roi", "return on investment"] },
  { name: "Startup Burn Rate Calculator", category: "Business", url: "/business-calculators/burn-rate-calculator/", keywords: ["burn rate", "startup", "runway"] },
  { name: "CAC Calculator", category: "Business", url: "/business-calculators/cac-calculator/", keywords: ["cac", "customer acquisition cost"] },
  { name: "LTV Calculator", category: "Business", url: "/business-calculators/ltv-calculator/", keywords: ["ltv", "lifetime value", "customer"] },
  { name: "Commission Calculator", category: "Business", url: "/business-calculators/commission-calculator/", keywords: ["commission", "sales commission"] },
  { name: "Sales Tax Calculator", category: "Business", url: "/business-calculators/sales-tax-calculator/", keywords: ["sales tax", "tax"] },
  { name: "Freelance Rate Calculator", category: "Business", url: "/business-calculators/freelance-rate-calculator/", keywords: ["freelance", "rate", "hourly rate"] },
  { name: "Pricing Calculator", category: "Business", url: "/business-calculators/pricing-calculator/", keywords: ["pricing", "price", "strategy"] },
  { name: "Revenue Growth Calculator", category: "Business", url: "/business-calculators/revenue-growth-calculator/", keywords: ["revenue", "growth", "mrr"] },
  { name: "Cash Runway Calculator", category: "Business", url: "/business-calculators/cash-runway-calculator/", keywords: ["cash runway", "burn", "startup"] },

  // Side Hustle
  { name: "Side Hustle Profit Calculator", category: "Side Hustle", url: "/side-hustle-calculators/side-hustle-profit-calculator/", keywords: ["side hustle", "profit", "income"] },
  { name: "Etsy Profit Calculator", category: "Side Hustle", url: "/side-hustle-calculators/etsy-profit-calculator/", keywords: ["etsy", "handmade", "seller profit"] },
  { name: "Amazon Seller Profit Calculator", category: "Side Hustle", url: "/side-hustle-calculators/amazon-seller-profit-calculator/", keywords: ["amazon", "fba", "seller profit"] },
  { name: "Dropshipping Profit Calculator", category: "Side Hustle", url: "/side-hustle-calculators/dropshipping-profit-calculator/", keywords: ["dropshipping", "ecommerce", "profit margin"] },
  { name: "YouTube Earnings Calculator", category: "Side Hustle", url: "/side-hustle-calculators/youtube-earnings-calculator/", keywords: ["youtube", "adsense", "creator earnings"] },
  { name: "TikTok Earnings Calculator", category: "Side Hustle", url: "/side-hustle-calculators/tiktok-earnings-calculator/", keywords: ["tiktok", "creator fund", "social media income"] },
  { name: "Freelance Hourly Rate Calculator", category: "Side Hustle", url: "/side-hustle-calculators/freelance-hourly-rate-calculator/", keywords: ["freelance", "hourly rate", "consulting"] },
  { name: "Delivery Driver Earnings Calculator", category: "Side Hustle", url: "/side-hustle-calculators/delivery-driver-earnings-calculator/", keywords: ["delivery", "doordash", "instacart earnings"] },
  { name: "Rideshare Income Calculator", category: "Side Hustle", url: "/side-hustle-calculators/rideshare-income-calculator/", keywords: ["rideshare", "uber", "lyft income"] },
  { name: "Online Course Profit Calculator", category: "Side Hustle", url: "/side-hustle-calculators/online-course-profit-calculator/", keywords: ["online course", "udemy", "course revenue"] },

  // Freelancer
  { name: "Freelance Tax Estimator", category: "Freelancer", url: "/freelancer-calculators/freelance-tax-estimator/", keywords: ["freelance tax", "self employment tax", "1099"] },
  { name: "Freelance Income Stability Calculator", category: "Freelancer", url: "/freelancer-calculators/freelance-income-stability-calculator/", keywords: ["income stability", "freelance income", "variable income"] },
  { name: "Project Pricing Calculator", category: "Freelancer", url: "/freelancer-calculators/project-pricing-calculator/", keywords: ["project pricing", "fixed fee", "freelance quote"] },
  { name: "Client Profitability Calculator", category: "Freelancer", url: "/freelancer-calculators/client-profitability-calculator/", keywords: ["client profit", "profitability", "client value"] },
  { name: "Freelance Break Even Calculator", category: "Freelancer", url: "/freelancer-calculators/freelance-break-even-calculator/", keywords: ["break even", "freelance overhead", "minimum income"] },
  { name: "Retainer Pricing Calculator", category: "Freelancer", url: "/freelancer-calculators/retainer-pricing-calculator/", keywords: ["retainer", "monthly fee", "recurring contract"] },
  { name: "Hourly to Annual Income Calculator", category: "Freelancer", url: "/freelancer-calculators/hourly-to-annual-income-calculator/", keywords: ["hourly to annual", "annual income", "rate conversion"] },
  { name: "Contractor vs Employee Income Calculator", category: "Freelancer", url: "/freelancer-calculators/contractor-vs-employee-income-calculator/", keywords: ["contractor vs employee", "w2 vs 1099", "take home pay"] },
  { name: "Freelance Utilization Rate Calculator", category: "Freelancer", url: "/freelancer-calculators/freelance-utilization-rate-calculator/", keywords: ["utilization rate", "billable hours", "capacity"] },
  { name: "Freelance Revenue Forecast Calculator", category: "Freelancer", url: "/freelancer-calculators/freelance-revenue-forecast-calculator/", keywords: ["revenue forecast", "freelance projection", "income planning"] },

  // Inflation
  { name: "Inflation Impact Calculator", category: "Inflation", url: "/inflation-calculators/inflation-impact-calculator/", keywords: ["inflation impact", "price increase", "cost of living"] },
  { name: "Future Purchasing Power Calculator", category: "Inflation", url: "/inflation-calculators/future-purchasing-power-calculator/", keywords: ["purchasing power", "future value", "inflation"] },
  { name: "Inflation-Adjusted Salary Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-salary-calculator/", keywords: ["real salary", "inflation adjusted", "wage growth"] },
  { name: "Inflation-Adjusted Savings Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-savings-calculator/", keywords: ["real savings", "inflation adjusted savings", "purchasing power"] },
  { name: "Cost Increase Projection Calculator", category: "Inflation", url: "/inflation-calculators/cost-increase-projection-calculator/", keywords: ["cost projection", "price forecast", "inflation rate"] },
  { name: "Inflation-Adjusted Retirement Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-retirement-calculator/", keywords: ["real retirement value", "inflation retirement", "nest egg"] },
  { name: "Inflation-Adjusted Rent Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-rent-calculator/", keywords: ["rent increase", "real rent", "housing inflation"] },
  { name: "Inflation-Adjusted Tuition Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-tuition-calculator/", keywords: ["tuition inflation", "college cost", "education inflation"] },
  { name: "Inflation-Adjusted Healthcare Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-healthcare-calculator/", keywords: ["healthcare inflation", "medical costs", "health insurance"] },
  { name: "Inflation-Adjusted Grocery Cost Calculator", category: "Inflation", url: "/inflation-calculators/inflation-adjusted-grocery-cost-calculator/", keywords: ["grocery inflation", "food costs", "CPI"] },

  // Wealth Building
  { name: "Net Worth Growth Calculator", category: "Wealth Building", url: "/wealth-building-calculators/net-worth-growth-calculator/", keywords: ["net worth", "wealth growth", "assets"] },
  { name: "Wealth Accumulation Calculator", category: "Wealth Building", url: "/wealth-building-calculators/wealth-accumulation-calculator/", keywords: ["wealth accumulation", "savings growth", "compound wealth"] },
  { name: "Compound Growth Calculator", category: "Wealth Building", url: "/wealth-building-calculators/compound-growth-calculator/", keywords: ["compound growth", "exponential growth", "investment"] },
  { name: "Investment Consistency Calculator", category: "Wealth Building", url: "/wealth-building-calculators/investment-consistency-calculator/", keywords: ["dollar cost averaging", "consistent investing", "DCA"] },
  { name: "Passive Income Growth Calculator", category: "Wealth Building", url: "/wealth-building-calculators/passive-income-growth-calculator/", keywords: ["passive income", "dividend growth", "cash flow"] },
  { name: "Asset Allocation Growth Calculator", category: "Wealth Building", url: "/wealth-building-calculators/asset-allocation-growth-calculator/", keywords: ["asset allocation", "portfolio growth", "diversification"] },
  { name: "Savings Acceleration Calculator", category: "Wealth Building", url: "/wealth-building-calculators/savings-acceleration-calculator/", keywords: ["savings rate", "accelerate savings", "fast track"] },
  { name: "Financial Momentum Calculator", category: "Wealth Building", url: "/wealth-building-calculators/financial-momentum-calculator/", keywords: ["financial momentum", "wealth trajectory", "progress"] },
  { name: "Wealth Milestone Calculator", category: "Wealth Building", url: "/wealth-building-calculators/wealth-milestone-calculator/", keywords: ["wealth milestone", "net worth goal", "financial goal"] },
  { name: "Millionaire Timeline Calculator", category: "Wealth Building", url: "/wealth-building-calculators/millionaire-timeline-calculator/", keywords: ["millionaire", "million dollars", "wealth timeline"] },

  // Minimalism and Budget
  { name: "Expense Reduction Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/expense-reduction-calculator/", keywords: ["expense reduction", "cut costs", "savings"] },
  { name: "Minimalist Lifestyle Savings Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/minimalist-lifestyle-savings-calculator/", keywords: ["minimalism", "lifestyle savings", "simple living"] },
  { name: "Subscription Reduction Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/subscription-reduction-calculator/", keywords: ["subscriptions", "cancel subscriptions", "monthly fees"] },
  { name: "Downsizing Savings Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/downsizing-savings-calculator/", keywords: ["downsizing", "smaller home", "cost savings"] },
  { name: "Monthly Spending Simplification Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/monthly-spending-simplification-calculator/", keywords: ["spending simplification", "budget simplify", "monthly expenses"] },
  { name: "Household Declutter Savings Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/household-declutter-savings-calculator/", keywords: ["declutter", "sell items", "household savings"] },
  { name: "Budget Optimization Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/budget-optimization-calculator/", keywords: ["budget optimization", "optimize spending", "best budget"] },
  { name: "Expense Efficiency Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/expense-efficiency-calculator/", keywords: ["expense efficiency", "value per dollar", "spending score"] },
  { name: "Spending Reduction Impact Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/spending-reduction-impact-calculator/", keywords: ["spending reduction", "savings impact", "cut spending"] },
  { name: "Lifestyle Cost Simplification Calculator", category: "Minimalism and Budget", url: "/minimalism-and-budget-calculators/lifestyle-cost-simplification-calculator/", keywords: ["lifestyle cost", "simple life", "reduce expenses"] },

  // Financial Independence
  { name: "Financial Independence Number Calculator", category: "Financial Independence", url: "/financial-independence-calculators/financial-independence-number-calculator/", keywords: ["FI number", "financial independence", "FIRE"] },
  { name: "Early Retirement Feasibility Calculator", category: "Financial Independence", url: "/financial-independence-calculators/early-retirement-feasibility-calculator/", keywords: ["early retirement", "FIRE feasibility", "retire early"] },
  { name: "Safe Withdrawal Rate Calculator", category: "Financial Independence", url: "/financial-independence-calculators/safe-withdrawal-rate-calculator/", keywords: ["safe withdrawal rate", "4% rule", "SWR"] },
  { name: "FIRE Timeline Calculator", category: "Financial Independence", url: "/financial-independence-calculators/fire-timeline-calculator/", keywords: ["FIRE timeline", "financial independence timeline", "retire early date"] },
  { name: "Lean FIRE Calculator", category: "Financial Independence", url: "/financial-independence-calculators/lean-fire-calculator/", keywords: ["lean FIRE", "frugal retirement", "minimal retirement"] },
  { name: "Coast FIRE Calculator", category: "Financial Independence", url: "/financial-independence-calculators/coast-fire-calculator/", keywords: ["coast FIRE", "coast FI", "coasting retirement"] },
  { name: "Barista FIRE Calculator", category: "Financial Independence", url: "/financial-independence-calculators/barista-fire-calculator/", keywords: ["barista FIRE", "part time retirement", "semi FIRE"] },
  { name: "Semi-Retirement Calculator", category: "Financial Independence", url: "/financial-independence-calculators/semi-retirement-calculator/", keywords: ["semi retirement", "partial retirement", "phased retirement"] },
  { name: "Financial Freedom Timeline Calculator", category: "Financial Independence", url: "/financial-independence-calculators/financial-freedom-timeline-calculator/", keywords: ["financial freedom", "freedom date", "FI date"] },
  { name: "Retirement Flexibility Calculator", category: "Financial Independence", url: "/financial-independence-calculators/retirement-flexibility-calculator/", keywords: ["retirement flexibility", "retirement options", "flexible retirement"] },

  // Money Psychology
  { name: "Spending Behavior Calculator", category: "Money Psychology", url: "/money-psychology-calculators/spending-behavior-calculator/", keywords: ["spending behavior", "money habits", "spending patterns"] },
  { name: "Impulse Purchase Impact Calculator", category: "Money Psychology", url: "/money-psychology-calculators/impulse-purchase-impact-calculator/", keywords: ["impulse buying", "impulse purchase", "unplanned spending"] },
  { name: "Financial Stress Score Calculator", category: "Money Psychology", url: "/money-psychology-calculators/financial-stress-score-calculator/", keywords: ["financial stress", "money anxiety", "stress score"] },
  { name: "Savings Discipline Calculator", category: "Money Psychology", url: "/money-psychology-calculators/savings-discipline-calculator/", keywords: ["savings discipline", "saving consistency", "habit score"] },
  { name: "Risk Tolerance Score Calculator", category: "Money Psychology", url: "/money-psychology-calculators/risk-tolerance-score-calculator/", keywords: ["risk tolerance", "investment risk", "risk profile"] },
  { name: "Money Habit Score Calculator", category: "Money Psychology", url: "/money-psychology-calculators/money-habit-score-calculator/", keywords: ["money habits", "financial habits", "habit score"] },
  { name: "Financial Confidence Score Calculator", category: "Money Psychology", url: "/money-psychology-calculators/financial-confidence-score-calculator/", keywords: ["financial confidence", "money mindset", "confidence score"] },
  { name: "Budget Adherence Calculator", category: "Money Psychology", url: "/money-psychology-calculators/budget-adherence-calculator/", keywords: ["budget adherence", "stick to budget", "budget compliance"] },
  { name: "Lifestyle Inflation Calculator", category: "Money Psychology", url: "/money-psychology-calculators/lifestyle-inflation-calculator/", keywords: ["lifestyle inflation", "lifestyle creep", "spending increase"] },
  { name: "Spending Awareness Calculator", category: "Money Psychology", url: "/money-psychology-calculators/spending-awareness-calculator/", keywords: ["spending awareness", "conscious spending", "mindful money"] },

  // Household Efficiency
  { name: "Utility Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/utility-savings-calculator/", keywords: ["utility savings", "lower bills", "household savings"] },
  { name: "Energy Efficiency Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/energy-efficiency-savings-calculator/", keywords: ["energy savings", "efficiency savings", "reduce energy"] },
  { name: "Water Usage Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/water-usage-savings-calculator/", keywords: ["water savings", "reduce water", "water bill"] },
  { name: "Grocery Waste Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/grocery-waste-savings-calculator/", keywords: ["food waste", "grocery savings", "meal planning"] },
  { name: "Home Efficiency Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/home-efficiency-savings-calculator/", keywords: ["home efficiency", "household costs", "home savings"] },
  { name: "Appliance Cost Comparison Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/appliance-cost-comparison-calculator/", keywords: ["appliance cost", "appliance comparison", "energy star"] },
  { name: "Heating Cost Efficiency Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/heating-cost-efficiency-calculator/", keywords: ["heating cost", "furnace efficiency", "winter bills"] },
  { name: "Cooling Cost Efficiency Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/cooling-cost-efficiency-calculator/", keywords: ["cooling cost", "AC efficiency", "summer bills"] },
  { name: "Household Maintenance Savings Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/household-maintenance-savings-calculator/", keywords: ["home maintenance", "preventive maintenance", "repair savings"] },
  { name: "Home Operating Cost Calculator", category: "Household Efficiency", url: "/household-efficiency-calculators/home-operating-cost-calculator/", keywords: ["home operating cost", "total home cost", "monthly home expenses"] },

  // Digital Income
  { name: "Affiliate Income Calculator", category: "Digital Income", url: "/digital-income-calculators/affiliate-income-calculator/", keywords: ["affiliate income", "affiliate marketing", "commission"] },
  { name: "Subscription Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/subscription-revenue-calculator/", keywords: ["subscription revenue", "MRR", "recurring revenue"] },
  { name: "SaaS Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/saas-revenue-calculator/", keywords: ["saas revenue", "software revenue", "ARR"] },
  { name: "Membership Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/membership-revenue-calculator/", keywords: ["membership site", "membership revenue", "community income"] },
  { name: "Digital Product Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/digital-product-revenue-calculator/", keywords: ["digital products", "ebook revenue", "downloads"] },
  { name: "Newsletter Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/newsletter-revenue-calculator/", keywords: ["newsletter revenue", "email list", "substack"] },
  { name: "Ad Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/ad-revenue-calculator/", keywords: ["ad revenue", "display ads", "CPM"] },
  { name: "Online Store Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/online-store-revenue-calculator/", keywords: ["online store", "ecommerce revenue", "shopify"] },
  { name: "Creator Revenue Calculator", category: "Digital Income", url: "/digital-income-calculators/creator-revenue-calculator/", keywords: ["creator economy", "content creator", "monetization"] },
  { name: "Platform Fee Calculator", category: "Digital Income", url: "/digital-income-calculators/platform-fee-calculator/", keywords: ["platform fees", "marketplace fees", "net revenue"] },

  // Life Event Financial
  { name: "Divorce Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/divorce-cost-calculator/", keywords: ["divorce cost", "legal fees", "separation"] },
  { name: "Adoption Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/adoption-cost-calculator/", keywords: ["adoption cost", "adoption fees", "foster"] },
  { name: "Moving Abroad Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/moving-abroad-cost-calculator/", keywords: ["moving abroad", "expat cost", "relocation international"] },
  { name: "Career Change Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/career-change-cost-calculator/", keywords: ["career change", "job transition", "retraining cost"] },
  { name: "Relocation Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/relocation-cost-calculator/", keywords: ["relocation", "moving cost", "new city"] },
  { name: "New Baby Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/new-baby-cost-calculator/", keywords: ["new baby", "baby cost", "childcare expenses"] },
  { name: "Wedding Savings Timeline Calculator", category: "Life Events", url: "/life-event-financial-calculators/wedding-savings-timeline-calculator/", keywords: ["wedding savings", "wedding budget", "save for wedding"] },
  { name: "College Decision Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/college-decision-cost-calculator/", keywords: ["college cost", "university decision", "tuition comparison"] },
  { name: "Gap Year Cost Calculator", category: "Life Events", url: "/life-event-financial-calculators/gap-year-cost-calculator/", keywords: ["gap year", "year off", "travel budget"] },
  { name: "Sabbatical Savings Calculator", category: "Life Events", url: "/life-event-financial-calculators/sabbatical-savings-calculator/", keywords: ["sabbatical", "career break", "time off savings"] }
];
